[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"

[directory]
style = "white"
truncation_length = 3

[username]
show_always = true
style_user = "dimmed white"
format = "[$user]($style) "

[hostname]
ssh_only = false
style = "dimmed white"
format = "[$hostname]($style) "

[git_branch]
symbol = " "
style = "dimmed white"
format = "[on](dimmed white) [$symbol$branch]($style) "

[git_status]
style = "bold rgb(200,80,80)"
format = "([$all_status$ahead_behind]($style)) "
