# Default values — matugen overwrites this file once you run it on a wallpaper.

background #0a0a0d
foreground #eaeaea

cursor #7dd3fc
cursor_text_color #0a0a0d

selection_background #eaeaea
selection_foreground #0a0a0d

active_tab_background #7dd3fc
active_tab_foreground #0a0a0d

url_color #7dd3fc
